language: python

python:
  - "3.7"

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - mopidy

env:
  - TOX_ENV=py37
  - TOX_ENV=flake8

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py37' ]; then pip install coveralls; coveralls; fi"
